name: landmark

channels:
  - conda-forge

dependencies:
  - python=3.10.6
  - matplotlib=3.6.0
  - pip
  - pip:
    - numpy==1.22.4
    - scipy==1.9.1
    - scikit-learn==1.1.2
    - ipykernel==6.16.0
    - bouter==0.2.0
    - flammkuchen==1.0.2
    - colorcet
    - tqdm